spring.application.name=demo

server.port = 9999
server.error.include-message=always

spring.datasource.url=jdbc:postgresql://ep-damp-salad-abl0xk11.eu-west-2.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_q2kx9NGZyeDc

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

project.base.url = http://localhost:9999